In [1]:
import numpy as np

In [2]:
area_in_cell_dim = 200

cell_x_id_array = np.random.randint(area_in_cell_dim, size=15)

In [3]:
np.repeat(a=cell_x_id_array, repeats=7)

array([ 39,  39,  39,  39,  39,  39,  39,   2,   2,   2,   2,   2,   2,
         2,  46,  46,  46,  46,  46,  46,  46, 143, 143, 143, 143, 143,
       143, 143, 106, 106, 106, 106, 106, 106, 106, 148, 148, 148, 148,
       148, 148, 148, 167, 167, 167, 167, 167, 167, 167,  63,  63,  63,
        63,  63,  63,  63, 130, 130, 130, 130, 130, 130, 130, 183, 183,
       183, 183, 183, 183, 183, 113, 113, 113, 113, 113, 113, 113,  47,
        47,  47,  47,  47,  47,  47,  51,  51,  51,  51,  51,  51,  51,
        10,  10,  10,  10,  10,  10,  10, 128, 128, 128, 128, 128, 128,
       128])

In [4]:
instance_x = cell_x_id_array * 5
instance_x = np.repeat(a=instance_x, repeats=7)
instance_x

array([195, 195, 195, 195, 195, 195, 195,  10,  10,  10,  10,  10,  10,
        10, 230, 230, 230, 230, 230, 230, 230, 715, 715, 715, 715, 715,
       715, 715, 530, 530, 530, 530, 530, 530, 530, 740, 740, 740, 740,
       740, 740, 740, 835, 835, 835, 835, 835, 835, 835, 315, 315, 315,
       315, 315, 315, 315, 650, 650, 650, 650, 650, 650, 650, 915, 915,
       915, 915, 915, 915, 915, 565, 565, 565, 565, 565, 565, 565, 235,
       235, 235, 235, 235, 235, 235, 255, 255, 255, 255, 255, 255, 255,
        50,  50,  50,  50,  50,  50,  50, 640, 640, 640, 640, 640, 640,
       640])

In [5]:
instance_x.shape

(105,)

In [6]:
np.random.uniform(high=5, size=10)

array([2.4733655 , 4.29311656, 4.12621502, 0.91758551, 4.31139402,
       4.07139483, 2.69774213, 3.44329386, 3.57096619, 2.1703848 ])

In [7]:
np.random.randint(low=4.3242, size=10)

array([1, 3, 2, 2, 1, 3, 0, 1, 3, 0])

In [8]:
type(instance_x.dtype)

numpy.dtype[int32]

In [9]:
instance_x.dtype

dtype('int32')

In [10]:
(cell_x_id_array * 5.4).dtype

dtype('float64')

In [11]:
np.repeat(a=np.arange(10), repeats=6)

array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3,
       3, 3, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 7, 7,
       7, 7, 7, 7, 8, 8, 8, 8, 8, 8, 9, 9, 9, 9, 9, 9])

In [12]:
np.tile(A=np.arange(10), reps=6)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1,
       2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3,
       4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
a = np.arange(10)
b = a.repeat(5)
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[0 0 0 0 0 1 1 1 1 1 2 2 2 2 2 3 3 3 3 3 4 4 4 4 4 5 5 5 5 5 6 6 6 6 6 7 7
 7 7 7 8 8 8 8 8 9 9 9 9 9]


In [14]:
a = np.arange(start=0, stop=10)
b = np.arange(start=50, stop=60)
c = np.arange(start=100, stop=110)

In [15]:
np.stack(arrays=(a, b, c), axis=-1)

array([[  0,  50, 100],
       [  1,  51, 101],
       [  2,  52, 102],
       [  3,  53, 103],
       [  4,  54, 104],
       [  5,  55, 105],
       [  6,  56, 106],
       [  7,  57, 107],
       [  8,  58, 108],
       [  9,  59, 109]])

In [16]:
np.stack(arrays=(a, b, c)).T

array([[  0,  50, 100],
       [  1,  51, 101],
       [  2,  52, 102],
       [  3,  53, 103],
       [  4,  54, 104],
       [  5,  55, 105],
       [  6,  56, 106],
       [  7,  57, 107],
       [  8,  58, 108],
       [  9,  59, 109]])

In [17]:
np.column_stack(tup=(a, b, c))

array([[  0,  50, 100],
       [  1,  51, 101],
       [  2,  52, 102],
       [  3,  53, 103],
       [  4,  54, 104],
       [  5,  55, 105],
       [  6,  56, 106],
       [  7,  57, 107],
       [  8,  58, 108],
       [  9,  59, 109]])

In [18]:
stacked = np.column_stack(tup=(a, b, c))
print(stacked)
np.savetxt(fname="test.txt", X=stacked, fmt=['%d', '%d', '%.6f'])

[[  0  50 100]
 [  1  51 101]
 [  2  52 102]
 [  3  53 103]
 [  4  54 104]
 [  5  55 105]
 [  6  56 106]
 [  7  57 107]
 [  8  58 108]
 [  9  59 109]]


In [19]:
a = np.arange(start=0, stop=10)
b = np.arange(start=50, stop=60)
c = np.arange(start=100, stop=110, dtype=np.float64)
stacked = np.column_stack(tup=(a, b, c))
print(stacked)
np.savetxt(fname="test.txt", X=stacked, fmt=['%d', '%d', '%.6f'])

[[  0.  50. 100.]
 [  1.  51. 101.]
 [  2.  52. 102.]
 [  3.  53. 103.]
 [  4.  54. 104.]
 [  5.  55. 105.]
 [  6.  56. 106.]
 [  7.  57. 107.]
 [  8.  58. 108.]
 [  9.  59. 109.]]


In [20]:
fmt = ' '.join(['%g']*stacked.shape[1])
fmt

'%g %g %g'

In [21]:
fmt = '%d %d %.6f\n'*stacked.shape[0]
fmt

'%d %d %.6f\n%d %d %.6f\n%d %d %.6f\n%d %d %.6f\n%d %d %.6f\n%d %d %.6f\n%d %d %.6f\n%d %d %.6f\n%d %d %.6f\n%d %d %.6f\n'

In [22]:
fmt % tuple(stacked.ravel())

'0 50 100.000000\n1 51 101.000000\n2 52 102.000000\n3 53 103.000000\n4 54 104.000000\n5 55 105.000000\n6 56 106.000000\n7 57 107.000000\n8 58 108.000000\n9 59 109.000000\n'

In [23]:
['%d %d %.6f'] * stacked.shape[0]

['%d %d %.6f',
 '%d %d %.6f',
 '%d %d %.6f',
 '%d %d %.6f',
 '%d %d %.6f',
 '%d %d %.6f',
 '%d %d %.6f',
 '%d %d %.6f',
 '%d %d %.6f',
 '%d %d %.6f']

In [24]:
a = np.arange(100, 110)
b = np.array([2, 4, 9])
a[b]

array([102, 104, 109])

In [25]:
x = np.random.uniform(high=100, size=20)
x

array([29.25553556, 50.90948837, 29.2235092 , 30.7563599 , 41.99498168,
       73.66472879, 76.46361333, 70.01751016, 69.65972767, 33.23888956,
       85.95271568, 13.58962161, 76.51990233, 79.79699827, 27.7630079 ,
       23.28581536, 60.42085462, 96.63791462,  9.01688768, 79.07103466])

In [26]:
x.dtype

dtype('float64')

In [27]:
y = x.astype(np.float64)
y

array([29.25553556, 50.90948837, 29.2235092 , 30.7563599 , 41.99498168,
       73.66472879, 76.46361333, 70.01751016, 69.65972767, 33.23888956,
       85.95271568, 13.58962161, 76.51990233, 79.79699827, 27.7630079 ,
       23.28581536, 60.42085462, 96.63791462,  9.01688768, 79.07103466])

In [28]:
y.dtype

dtype('float64')

In [29]:
number = np.array([2, 5, 3, 7])
start = np.array([100, 50, 5, 150])

In [33]:
a = np.arange(start=start, stop=start+number)
a

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [34]:
start + number

array([102,  55,   8, 157])

In [35]:
a = np.arange(start=0, stop=10)
b = np.arange(start=50, stop=55)
c = np.arange(start=100, stop=120)
arrays = [a, b, c]
arrays

[array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([50, 51, 52, 53, 54]),
 array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
        113, 114, 115, 116, 117, 118, 119])]

In [36]:
np.concatenate(arrays)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  50,  51,  52,
        53,  54, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110,
       111, 112, 113, 114, 115, 116, 117, 118, 119])

In [39]:
start = np.array([0, 50, 100])
length = np.array([10, 5, 20])
start, length

(array([  0,  50, 100]), array([10,  5, 20]))

In [41]:
length.cumsum()

array([10, 15, 35])

In [42]:
start + length - length.cumsum()

array([ 0, 40, 85])

In [43]:
np.repeat(start + length - length.cumsum(), length)

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 40, 40, 40, 40, 40, 85, 85,
       85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85, 85,
       85])

In [44]:
np.arange(length.sum())

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34])

In [45]:
np.repeat(start + length - length.cumsum(), length) + np.arange(length.sum())

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  50,  51,  52,
        53,  54, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110,
       111, 112, 113, 114, 115, 116, 117, 118, 119])

In [8]:
x = np.array([])
x

array([], dtype=float64)

In [9]:
def f(x):
    print(x)
    x[4] = 999
    print(x)

In [11]:
a = np.arange(10)
print(a)
print("funkcja")
f(a)
print("po funkcji")
print(a)

[0 1 2 3 4 5 6 7 8 9]
funkcja
[0 1 2 3 4 5 6 7 8 9]
[  0   1   2   3 999   5   6   7   8   9]
po funkcji
[  0   1   2   3 999   5   6   7   8   9]


In [22]:
x = np.zeros(2, dtype=np.int32)
x

array([0, 0])

In [23]:
x[1] += 1
x[0] += 1
x[1] += 1
x

array([1, 2])

In [2]:
a = np.array([1, 2, 6, 3, 2, 4, 6, 2, 3, 4, 6, 3, 2, 5, 2, 3, 1, 5, 3])
np.unique(ar=a, return_index=True, return_inverse=True, return_counts=True)

(array([1, 2, 3, 4, 5, 6]),
 array([ 0,  1,  3,  5, 13,  2], dtype=int64),
 array([0, 1, 5, 2, 1, 3, 5, 1, 2, 3, 5, 2, 1, 4, 1, 2, 0, 4, 2],
       dtype=int64),
 array([2, 5, 5, 2, 2, 3], dtype=int64))

In [3]:
a = np.array([1, 2, 6, 3, 2, 4, 6, 2, 3, 4, 6, 3, 2, 5, 2, 3, 1, 5, 3])
np.unique(ar=a, return_counts=True)

(array([1, 2, 3, 4, 5, 6]), array([2, 5, 5, 2, 2, 3], dtype=int64))

In [5]:
(unique, counts) = np.unique(ar=a, return_counts=True)
counts

array([2, 5, 5, 2, 2, 3], dtype=int64)

In [11]:
ndf = 4
ndfn = 30
last_colloc_id = 10
additional_noise_feature = np.random.randint(low=ndf, size=ndfn) + last_colloc_id
additional_noise_feature

array([11, 13, 12, 11, 12, 12, 10, 10, 12, 10, 13, 11, 11, 11, 12, 13, 11,
       12, 11, 13, 11, 10, 12, 10, 11, 11, 11, 13, 12, 10])

In [12]:
(unique, counts) = np.unique(ar=additional_noise_feature, return_counts=True)
counts

array([ 6, 11,  8,  5], dtype=int64)

In [20]:
x = np.repeat(counts - counts.cumsum(), counts) + np.arange(counts.sum())
x

array([ 0,  1,  2,  3,  4,  5,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10,
        0,  1,  2,  3,  4,  5,  6,  7,  0,  1,  2,  3,  4], dtype=int64)

In [21]:
x

array([ 0,  1,  2,  3,  4,  5,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10,
        0,  1,  2,  3,  4,  5,  6,  7,  0,  1,  2,  3,  4], dtype=int64)

In [18]:
np.random.shuffle(x)

In [22]:
a = np.repeat(unique, counts)
a

array([10, 10, 10, 10, 10, 10, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11,
       12, 12, 12, 12, 12, 12, 12, 12, 13, 13, 13, 13, 13])

In [69]:
xa = np.column_stack(tup=(x, a))
xa

array([[ 0, 10],
       [ 1, 10],
       [ 2, 10],
       [ 3, 10],
       [ 4, 10],
       [ 5, 10],
       [ 0, 11],
       [ 1, 11],
       [ 2, 11],
       [ 3, 11],
       [ 4, 11],
       [ 5, 11],
       [ 6, 11],
       [ 7, 11],
       [ 8, 11],
       [ 9, 11],
       [10, 11],
       [ 0, 12],
       [ 1, 12],
       [ 2, 12],
       [ 3, 12],
       [ 4, 12],
       [ 5, 12],
       [ 6, 12],
       [ 7, 12],
       [ 0, 13],
       [ 1, 13],
       [ 2, 13],
       [ 3, 13],
       [ 4, 13]], dtype=int64)

In [70]:
np.random.shuffle(xa)
xa

array([[10, 11],
       [ 2, 12],
       [ 0, 12],
       [ 1, 11],
       [ 4, 12],
       [ 1, 12],
       [ 5, 11],
       [ 3, 13],
       [ 1, 13],
       [ 3, 11],
       [ 4, 11],
       [ 7, 11],
       [ 1, 10],
       [ 3, 10],
       [ 8, 11],
       [ 9, 11],
       [ 5, 10],
       [ 2, 11],
       [ 0, 13],
       [ 6, 12],
       [ 2, 13],
       [ 6, 11],
       [ 4, 10],
       [ 0, 11],
       [ 3, 12],
       [ 0, 10],
       [ 4, 13],
       [ 7, 12],
       [ 2, 10],
       [ 5, 12]], dtype=int64)

In [2]:
?np.random.randint

In [3]:
?np.random.uniform

In [18]:
np.random.uniform(size=10)

array([0.46376512, 0.29341507, 0.84607751, 0.488735  , 0.95597346,
       0.70636899, 0.47460146, 0.99962915, 0.98133157, 0.66829885])

In [26]:
np.random.uniform()

0.736954427522925

In [3]:
for i in range(10):
    print(i)
    i += 2
    print("again: %d" % i)

0
again: 2
1
again: 3
2
again: 4
3
again: 5
4
again: 6
5
again: 7
6
again: 8
7
again: 9
8
again: 10
9
again: 11


In [36]:
clumpy = 4
size = 13
x = np.random.randint(200, size=(size - 1) // clumpy + 1)
x

array([ 35,  96, 120,   3])

In [37]:
y = np.repeat(a=x, repeats=clumpy)
y

array([ 35,  35,  35,  35,  96,  96,  96,  96, 120, 120, 120, 120,   3,
         3,   3,   3])

In [38]:
y[:size]

array([ 35,  35,  35,  35,  96,  96,  96,  96, 120, 120, 120, 120,   3])

In [39]:
y = y[:size]
y

array([ 35,  35,  35,  35,  96,  96,  96,  96, 120, 120, 120, 120,   3])