In [1]:
import numpy as np

In [2]:
area_in_cell_dim = 200

cell_x_id_array = np.random.randint(area_in_cell_dim, size=15)

In [3]:
np.repeat(a=cell_x_id_array, repeats=7)

array([ 28,  28,  28,  28,  28,  28,  28, 170, 170, 170, 170, 170, 170,
       170,  33,  33,  33,  33,  33,  33,  33, 149, 149, 149, 149, 149,
       149, 149,   3,   3,   3,   3,   3,   3,   3, 198, 198, 198, 198,
       198, 198, 198, 135, 135, 135, 135, 135, 135, 135,  27,  27,  27,
        27,  27,  27,  27,   7,   7,   7,   7,   7,   7,   7, 178, 178,
       178, 178, 178, 178, 178, 147, 147, 147, 147, 147, 147, 147, 120,
       120, 120, 120, 120, 120, 120,  56,  56,  56,  56,  56,  56,  56,
        14,  14,  14,  14,  14,  14,  14, 190, 190, 190, 190, 190, 190,
       190])

In [4]:
instance_x = cell_x_id_array * 5
instance_x = np.repeat(a=instance_x, repeats=7)
instance_x

array([140, 140, 140, 140, 140, 140, 140, 850, 850, 850, 850, 850, 850,
       850, 165, 165, 165, 165, 165, 165, 165, 745, 745, 745, 745, 745,
       745, 745,  15,  15,  15,  15,  15,  15,  15, 990, 990, 990, 990,
       990, 990, 990, 675, 675, 675, 675, 675, 675, 675, 135, 135, 135,
       135, 135, 135, 135,  35,  35,  35,  35,  35,  35,  35, 890, 890,
       890, 890, 890, 890, 890, 735, 735, 735, 735, 735, 735, 735, 600,
       600, 600, 600, 600, 600, 600, 280, 280, 280, 280, 280, 280, 280,
        70,  70,  70,  70,  70,  70,  70, 950, 950, 950, 950, 950, 950,
       950])

In [5]:
instance_x.shape

(105,)

In [6]:
np.random.uniform(high=5, size=10)

array([1.78278536, 1.27997298, 3.83534754, 3.57578271, 1.53525029,
       1.31937879, 0.3560426 , 3.75060282, 3.652266  , 3.92162062])

In [7]:
np.random.randint(low=4.3242, size=10)

array([2, 2, 1, 3, 0, 2, 1, 3, 3, 3])

In [8]:
type(instance_x.dtype)

numpy.dtype[int32]

In [9]:
instance_x.dtype

dtype('int32')

In [10]:
(cell_x_id_array * 5.4).dtype

dtype('float64')

In [11]:
np.repeat(a=np.arange(10), repeats=6)

array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3,
       3, 3, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 7, 7,
       7, 7, 7, 7, 8, 8, 8, 8, 8, 8, 9, 9, 9, 9, 9, 9])

In [12]:
np.tile(A=np.arange(10), reps=6)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1,
       2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3,
       4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
a = np.arange(10)
b = a.repeat(5)
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[0 0 0 0 0 1 1 1 1 1 2 2 2 2 2 3 3 3 3 3 4 4 4 4 4 5 5 5 5 5 6 6 6 6 6 7 7
 7 7 7 8 8 8 8 8 9 9 9 9 9]


In [30]:
a = np.arange(start=0, stop=10)
b = np.arange(start=50, stop=60)
c = np.arange(start=100, stop=110)

In [31]:
np.stack(arrays=(a, b, c), axis=-1)

array([[  0,  50, 100],
       [  1,  51, 101],
       [  2,  52, 102],
       [  3,  53, 103],
       [  4,  54, 104],
       [  5,  55, 105],
       [  6,  56, 106],
       [  7,  57, 107],
       [  8,  58, 108],
       [  9,  59, 109]])

In [32]:
np.stack(arrays=(a, b, c)).T

array([[  0,  50, 100],
       [  1,  51, 101],
       [  2,  52, 102],
       [  3,  53, 103],
       [  4,  54, 104],
       [  5,  55, 105],
       [  6,  56, 106],
       [  7,  57, 107],
       [  8,  58, 108],
       [  9,  59, 109]])

In [33]:
np.column_stack(tup=(a, b, c))

array([[  0,  50, 100],
       [  1,  51, 101],
       [  2,  52, 102],
       [  3,  53, 103],
       [  4,  54, 104],
       [  5,  55, 105],
       [  6,  56, 106],
       [  7,  57, 107],
       [  8,  58, 108],
       [  9,  59, 109]])

In [34]:
stacked = np.column_stack(tup=(a, b, c))
print(stacked)
np.savetxt(fname="test.txt", X=stacked, fmt=['%d', '%d', '%.6f'])

[[  0  50 100]
 [  1  51 101]
 [  2  52 102]
 [  3  53 103]
 [  4  54 104]
 [  5  55 105]
 [  6  56 106]
 [  7  57 107]
 [  8  58 108]
 [  9  59 109]]


In [38]:
a = np.arange(start=0, stop=10)
b = np.arange(start=50, stop=60)
c = np.arange(start=100, stop=110, dtype=np.float64)
stacked = np.column_stack(tup=(a, b, c))
print(stacked)
np.savetxt(fname="test.txt", X=stacked, fmt=['%d', '%d', '%.6f'])

[[  0.  50. 100.]
 [  1.  51. 101.]
 [  2.  52. 102.]
 [  3.  53. 103.]
 [  4.  54. 104.]
 [  5.  55. 105.]
 [  6.  56. 106.]
 [  7.  57. 107.]
 [  8.  58. 108.]
 [  9.  59. 109.]]


In [39]:
stacked.shapefmt = ' '.join(['%g']*dataMat3.shape[1])

(10, 3)

In [43]:
fmt = ' '.join(['%g']*stacked.shape[1])
fmt

'%g %g %g'

In [54]:
fmt = '%d %d %.6f\n'*stacked.shape[0]
fmt

'%d %d %.6f\n%d %d %.6f\n%d %d %.6f\n%d %d %.6f\n%d %d %.6f\n%d %d %.6f\n%d %d %.6f\n%d %d %.6f\n%d %d %.6f\n%d %d %.6f\n'

In [55]:
fmt % tuple(stacked.ravel())

'0 50 100.000000\n1 51 101.000000\n2 52 102.000000\n3 53 103.000000\n4 54 104.000000\n5 55 105.000000\n6 56 106.000000\n7 57 107.000000\n8 58 108.000000\n9 59 109.000000\n'

In [52]:
['%d %d %.6f'] * stacked.shape[0]

['%d %d %.6f',
 '%d %d %.6f',
 '%d %d %.6f',
 '%d %d %.6f',
 '%d %d %.6f',
 '%d %d %.6f',
 '%d %d %.6f',
 '%d %d %.6f',
 '%d %d %.6f',
 '%d %d %.6f']

In [ ]:
fmt = ' '.join(['%g']*dataMat3.shape[1])
fmt = '\n'.join([fmt]*dataMat3.shape[0])
data = fmt % tuple(dataMat3.ravel())        
f.write(data)